### ISSUE TITLE
Mod crashes while trying to access multiplayer server

### ISSUE THREAD

**Issue by dibolek** [Developer-Mike/Autototem-Fabric#7]
Minecraft 1.20.2

First log from non-premium TLauncher clean fabric install (manual server login):
[latest.log](https://github.com/Developer-Mike/Autototem-Fabric/files/13800973/latest.log)

Second log premium version automatic login:
[latest.log](https://github.com/Developer-Mike/Autototem-Fabric/files/13800975/latest.log)

**Comment by Developer-Mike** [comment]
Can't reproduce this crash. Tested on a 1.20.2 multiplayer server with autototem version 1.20.4-1.0.3

**Comment by Developer-Mike** [comment]
Probably related to #8 and fixed with #9.
Got released in version `1.0.4` ([Modrinth](https://modrinth.com/mod/autototem/version/1.0.4))
